server:
  port: 8081
  servlet:
    session:
      cookie:
        name: OAUTH-CLIENT01

oauth2-server-url: http://localhost:8080
security:
  oauth2:
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key
    client:
      client-id: client001
      client-secret: 123123
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token

spring:
  main:
    allow-bean-definition-overriding: true

debug: true

logging:
  level:
    org.springframework.security: debug

